import { readFileSync, writeFileSync, renameSync, readdirSync } from 'fs';
import { join } from 'path';

const distAssets = join(process.cwd(), 'dist', 'assets');
const ts = Date.now().toString(36);

// Rename JS files to include timestamp, forcing new filenames
const jsFiles = readdirSync(distAssets).filter(f => f.endsWith('.js'));
const renameMap = {};
for (const file of jsFiles) {
  const newName = file.replace('.js', `-${ts}.js`);
  renameSync(join(distAssets, file), join(distAssets, newName));
  renameMap[file] = newName;
  console.log(`Renamed: ${file} -> ${newName}`);
}

// Update index.html to reference new filenames
const indexPath = join(process.cwd(), 'dist', 'index.html');
let html = readFileSync(indexPath, 'utf-8');
for (const [oldName, newName] of Object.entries(renameMap)) {
  html = html.replace(oldName, newName);
}
writeFileSync(indexPath, html);
console.log('Updated index.html references');

// Regenerate worker/spa_html.ts with updated index.html
const escaped = html.replace(/`/g, '\\`').replace(/\$/g, '\\$');
const output = `// Auto-generated - DO NOT EDIT\n// Generated by scripts/postbuild.mjs\nexport const SPA_HTML = \`${escaped}\`;\n`;
const spaPath = join(process.cwd(), 'worker', 'spa_html.ts');
writeFileSync(spaPath, output);
console.log('Regenerated worker/spa_html.ts');
