#!/usr/bin/env node
// Post-build script: inject dist/index.html into the worker
import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';

const html = readFileSync(join(process.cwd(), 'dist', 'index.html'), 'utf8');
const escaped = html.replace(/`/g, '\\`').replace(/\$/g, '\\$');
const output = `// Auto-generated - DO NOT EDIT\n// Generated by scripts/postbuild.mjs\nexport const SPA_HTML = \`${escaped}\`;\n`;

const outPath = join(process.cwd(), 'worker', 'spa_html.ts');
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, output);
console.log('Generated worker/spa_html.ts with current dist/index.html');
