// Auto-generated - DO NOT EDIT
// Generated by scripts/postbuild.mjs
export const SPA_HTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Fiction Hall — Fiction Writing Platform</title>
  <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
  <link rel="apple-touch-icon" href="/favicon.svg" />
  <script type="module" crossorigin src="/assets/index-525bBp4s-mrq7gmod.js"></script>
  <link rel="stylesheet" crossorigin href="/assets/index-BGC9pMXq.css">
</head>
<body>
  <div id="root"></div>
</body>
</html>
`;
