// Auto-generated - DO NOT EDIT
// Generated by scripts/postbuild.mjs
export const SPA_HTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Nocative — Fiction Writing Platform</title>
  <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
  <script type="module" crossorigin src="/assets/index-igdzDJQ5-mpe8ja6b.js"></script>
  <link rel="stylesheet" crossorigin href="/assets/index-AQuxpjpl.css">
</head>
<body>
  <div id="root"></div>
</body>
</html>
`;
